# Stubs for passlib.crypto._blowfish (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.crypto._blowfish.unrolled import BlowfishEngine as BlowfishEngine
from typing import Any

def raw_bcrypt(password: Any, ident: Any, salt: Any, log_rounds: Any): ...
