# Stubs for passlib.crypto._blowfish.unrolled (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.crypto._blowfish.base import BlowfishEngine as _BlowfishEngine
from typing import Any

class BlowfishEngine(_BlowfishEngine):
    def encipher(self, l: Any, r: Any): ...
    def expand(self, key_words: Any) -> None: ...
