# Stubs for urllib3.poolmanager (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple

PoolKey = namedtuple('PoolKey', <ERROR>)

# NOTE: omitted the rest of the generated stub here, because it's irrelevant
