# Stubs for passlib.tests._test_bad_register (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import passlib.utils.handlers as uh

class dummy_bad(uh.StaticHandler):
    name: str = ...

class alt_dummy_bad(uh.StaticHandler):
    name: str = ...
