# Stubs for passlib.tests.backports (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest2 as unittest
from typing import Any

skip: Any
skipIf: Any
skipUnless: Any

class TestCase(unittest.TestCase):
    assertRegex: Any = ...
    assertRaisesRegex: Any = ...
