# Stubs for passlib.tests.test_win32 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.tests.utils import TestCase

class UtilTest(TestCase):
    def setUp(self) -> None: ...
    def test_lmhash(self) -> None: ...
    def test_nthash(self) -> None: ...
