# Stubs for passlib.tests.test_handlers_scrypt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.tests.utils import HandlerCase
from typing import Any

log: Any

class _scrypt_test(HandlerCase):
    handler: Any = ...
    known_correct_hashes: Any = ...
    known_malformed_hashes: Any = ...
    def setUpWarnings(self) -> None: ...
    def populate_settings(self, kwds: Any) -> None: ...
    class FuzzHashGenerator(HandlerCase.FuzzHashGenerator):
        def random_rounds(self): ...

scrypt_scrypt_test: Any
scrypt_builtin_test: Any
