# Stubs for passlib.tests.test_hosts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.tests.utils import TestCase
from typing import Any

log: Any

class HostsTest(TestCase):
    def check_unix_disabled(self, ctx: Any) -> None: ...
    def test_linux_context(self) -> None: ...
    def test_bsd_contexts(self) -> None: ...
    def test_host_context(self): ...
