# Stubs for passlib.tests.test_utils_md4 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.tests.test_crypto_builtin_md4 import _Common_MD4_Test

class Legacy_MD4_Test(_Common_MD4_Test):
    descriptionPrefix: str = ...
    def setUp(self) -> None: ...
    def get_md4_const(self): ...
