# Stubs for passlib.tests.tox_support (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

root_dir: Any
log: Any
TH_PATH: str

def do_hash_tests(*args: Any): ...
def do_preset_tests(name: Any) -> None: ...
def do_setup_gae(path: Any, runtime: Any) -> None: ...
def main(cmd: Any, *args: Any): ...
