from typing import Any, overload

from .decorators import identity_decorator

def matching_function(foo: int, bar: str) -> str: ...
def additional_args(foo: int) -> str: ...
def additional_optional_args(foo: int) -> Any: ...
@overload
def overloaded_additional_args(foo: str) -> Any: ...
@overload
def overloaded_additional_args(foo: int, bar: int) -> Any: ...
@overload
def overloaded_additional_optional_args(foo: str) -> Any: ...
@overload
def overloaded_additional_optional_args(foo: int, bar: int) -> Any: ...

@identity_decorator
def decorated_function(foo: Any): ...

@identity_decorator
def decorated_with_additional_args(foo: Any) -> Any: ...

@identity_decorator
def decorated_with_additional_optional_args(foo: Any) -> Any: ...