# Stubs for passlib.utils.des (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def mdes_encrypt_int_block(key: Any, input: Any, salt: int = ..., rounds: int = ...): ...
