# Stubs for passlib.utils.pbkdf2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.crypto.digest import norm_hash_name as norm_hash_name
from typing import Any, Optional

def get_prf(name: Any): ...
def pbkdf1(secret: Any, salt: Any, rounds: Any, keylen: Optional[Any] = ..., hash: str = ...): ...
def pbkdf2(secret: Any, salt: Any, rounds: Any, keylen: Optional[Any] = ..., prf: str = ...): ...
