# Stubs for passlib.crypto.des (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def expand_des_key(key: Any): ...
def des_encrypt_block(key: Any, input: Any, salt: int = ..., rounds: int = ...): ...
