# Stubs for passlib.crypto.scrypt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def validate(n: Any, r: Any, p: Any): ...
def scrypt(secret: Any, salt: Any, n: Any, r: Any, p: int = ..., keylen: int = ...): ...
