# Stubs for passlib.apps (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

custom_app_context: Any
django_context = django110_context
ldap_nocrypt_context: Any
ldap_context: Any
mysql3_context: Any
mysql4_context: Any
mysql_context = mysql4_context
postgres_context: Any
phpass_context: Any
phpbb3_context: Any
