# Stubs for passlib.hosts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

linux_context: Any
linux2_context: Any
freebsd_context: Any
openbsd_context: Any
netbsd_context: Any
host_context: Any
