# Stubs for passlib.ifc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class PasswordHash:
    is_disabled = ...  # type: bool
    truncate_size = ...  # type: Any
    truncate_error = ...  # type: bool
    truncate_verify_reject = ...  # type: bool
    @classmethod
    def hash(cls, secret: Any, **setting_and_context_kwds: Any) -> Any: ...
    @classmethod
    def encrypt(cls, *args: Any, **kwds: Any) -> Any: ...
    @classmethod
    def verify(cls, secret: Any, hash: Any, **context_kwds: Any) -> Any: ...
    @classmethod
    def using(cls, relaxed: bool = ..., **kwds: Any) -> Any: ...
    @classmethod
    def needs_update(cls, hash: Any, secret: Optional[Any] = ...) -> Any: ...
    @classmethod
    def identify(cls, hash: Any) -> Any: ...
    @classmethod
    def genconfig(cls, **setting_kwds: Any) -> Any: ...
    @classmethod
    def genhash(cls, secret: Any, config: Any, **context: Any) -> Any: ...
    deprecated = ...  # type: bool

class DisabledHash(PasswordHash):
    is_disabled = ...  # type: bool
    @classmethod
    def disable(cls, hash: Optional[Any] = ...) -> Any: ...
    @classmethod
    def enable(cls, hash: Any) -> Any: ...
