# Stubs for passlib.win32 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from passlib.hash import nthash as nthash
from typing import Any

raw_nthash: Any

def raw_lmhash(secret: Any, encoding: str = ..., hex: bool = ...): ...
