# Stubs for elasticsearch.client.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SKIP_IN_PATH: Any
GLOBAL_PARAMS: Any


def query_params(*es_query_params): ...


class NamespacedClient:
    client: Any = ...

    def __init__(self, client) -> None: ...

    @property
    def transport(self): ...


class AddonClient(NamespacedClient):
    @classmethod
    def infect_client(cls, client): ...
