from typing import Any

class FrozenInstanceError(AttributeError):
    msg: str = ...
    args: Any = ...

class AttrsAttributeNotFoundError(ValueError): ...
class NotAnAttrsClassError(ValueError): ...
class DefaultAlreadySetError(RuntimeError): ...
class UnannotatedAttributeError(RuntimeError): ...
class PythonTooOldError(RuntimeError): ...

class NotCallableError(TypeError):
    msg: Any = ...
    value: Any = ...
    def __init__(self, msg: Any, value: Any) -> None: ...
    def __str__(self): ...
