from typing import Any, Optional

class bcrypt:
    @classmethod
    def using(
        cls, relaxed: bool = ..., rounds: Optional[int] = None, **kwds: Any
    ) -> "bcrypt": ...
    @classmethod
    def identify(cls, hash: bytes) -> str: ...
    @classmethod
    def verify(cls, secret: str, hash: str) -> None: ...
    @classmethod
    def encrypt(cls, secret: str) -> None: ...
    @classmethod
    def hash(cls, secret: str) -> str: ...

class md5_crypt:
    @classmethod
    def using(
        cls, relaxed: bool = False, rounds: Optional[int] = None
    ) -> "md5_crypt": ...
    @classmethod
    def identify(cls, hash: bytes) -> str: ...
    @classmethod
    def verify(cls, secret: str, hash: str) -> None: ...
    @classmethod
    def encrypt(cls, secret: str) -> None: ...
    @classmethod
    def hash(cls, secret: str) -> str: ...
