# Stubs for elasticsearch (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


from typing import Any

VERSION: Any
__version__ = VERSION
__versionstr__: Any
logger: Any
