# Stubs for passlib.handlers.md5_crypt (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from passlib.utils import handlers as uh

class _MD5_Common(uh.HasSalt, uh.GenericHandler):
    setting_kwds = ...  # type: Any
    checksum_size = ...  # type: int
    checksum_chars = ...  # type: Any
    max_salt_size = ...  # type: int
    salt_chars = ...  # type: Any
    def to_string(self) -> Any: ...

class md5_crypt(uh.HasManyBackends, _MD5_Common):
    name = ...  # type: str
    ident = ...  # type: Any
    backends = ...  # type: Any

class apr_md5_crypt(_MD5_Common):
    name = ...  # type: str
    ident = ...  # type: Any
