# Stubs for passlib.handlers.misc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from passlib import ifc
from passlib.utils import handlers as uh

class unix_fallback(ifc.DisabledHash, uh.StaticHandler):
    name = ...  # type: str
    context_kwds = ...  # type: Any
    @classmethod
    def identify(cls, hash: Any) -> Any: ...
    enable_wildcard = ...  # type: Any
    def __init__(self, enable_wildcard: bool = ..., **kwds: Any) -> None: ...

class unix_disabled(ifc.DisabledHash, uh.MinimalHandler):
    name = ...  # type: str
    setting_kwds = ...  # type: Any
    context_kwds = ...  # type: Any
    default_marker = ...  # type: Any
    @classmethod
    def identify(cls, hash: Any) -> Any: ...
    @classmethod
    def hash(cls, secret: Any, **kwds: Any) -> Any: ...
    @classmethod
    def disable(cls, hash: Optional[Any] = ...) -> Any: ...
    @classmethod
    def enable(cls, hash: Any) -> Any: ...

class plaintext(uh.MinimalHandler):
    name = ...  # type: str
    setting_kwds = ...  # type: Any
    context_kwds = ...  # type: Any
    default_encoding = ...  # type: str
    @classmethod
    def identify(cls, hash: Any) -> Any: ...
