# Stubs for passlib.handlers.sha2_crypt (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from passlib.utils import handlers as uh

class _SHA2_Common(uh.HasManyBackends, uh.HasRounds, uh.HasSalt, uh.GenericHandler):
    setting_kwds = ...  # type: Any
    checksum_chars = ...  # type: Any
    max_salt_size = ...  # type: int
    salt_chars = ...  # type: Any
    min_rounds = ...  # type: int
    max_rounds = ...  # type: int
    rounds_cost = ...  # type: str
    implicit_rounds = ...  # type: bool
    def __init__(self, implicit_rounds: Optional[Any] = ..., **kwds: Any) -> None: ...
    def to_string(self) -> Any: ...
    backends = ...  # type: Any

class sha256_crypt(_SHA2_Common):
    name = ...  # type: str
    ident = ...  # type: Any
    checksum_size = ...  # type: int
    default_rounds = ...  # type: int

class sha512_crypt(_SHA2_Common):
    name = ...  # type: str
    ident = ...  # type: Any
    checksum_size = ...  # type: int
    default_rounds = ...  # type: int
